name: actitime_client
description: A set of classes to interact with ActiTime API.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ^5.1.1
  test: ^1.24.0

false_secrets:
  - /test/test_credentials.dart
